export const FETCH_REDDITS_REQUEST = 'FETCH_REDDITS_REQUEST'
export const FETCH_REDDITS_SUCCESS = 'FETCH_REDDITS_SUCCESS'
export const FETCH_REDDITS_FAILURE = 'FETCH_REDDITS_FAILURE'

export const COMMENTS_NEW_REQUEST = 'COMMENTS_NEW_REQUEST'
export const COMMENTS_NEW_SUCCESS = 'COMMENTS_NEW_SUCCESS'
export const COMMENTS_NEW_FAILURE = 'COMMENTS_NEW_FAILURE'
